export const welcomePageProjects = [
  {
    sl: 1,
    title: "Casa Palmera",
    url: "casa_palmera",
    mainImageURL: "https://res.cloudinary.com/dmcpyhafc/image/upload/v1728557918/right_view_eogbmb.jpg",
    subHeading1URL: "",
    subHeading2URL: "",
    sliderURLs: [],
    content: `This is a Turnkey construction project, we delivered with our best efforts and qualities. This project is situated in AIIMS Nagar Patrapada, Bhubaneswar. This is a 5-storey apartment with 20 units of 2 BHK and 3 BHK Flats. Total Built up area of this project is 28,000 sq.ft.`,
  },
  {
    sl: 2,
    title: "GP Nalini Grandeur",
    url: "gp_nalini_grandeur",
    mainImageURL: "https://res.cloudinary.com/dmcpyhafc/image/upload/v1728557918/right_view_eogbmb.jpg",
    subHeading1URL: "",
    subHeading2URL: "",
    sliderURLs: [],
    content: `Welcome to a place where a plush lifestyle awaits you to embrace you love and peace. A place where you will enjoy every moment with glory. GP Nalini Grandeur is a heavenly tale of 4 storeyed apartment situated near to Biju pattanaik International Airport, Bhubaneswar. Designed for ample light and ventilation.`,
  },
  {
    sl: 3,
    title: "GP Platinum",
    url: "gp_platinum",
    mainImageURL: "",
    subHeading1URL: "",
    subHeading2URL: "",
    sliderURLs: [],
    content: `A landmark for luxury lifestyle, where we delivered specious 3 BHK Vastu compliant flats. This is a 3-storey apartment established near to KIIT Square. The best part of this project is, we just completed this project in 10 months only.`,
  },
  {
    sl: 4,
    title: "Almo Residency",
    url: "almo_residency",
    mainImageURL: "",
    subHeading1URL: "",
    subHeading2URL: "",
    sliderURLs: [],
    content: `This is a Turnkey construction project, we delivered with our best efforts and qualities. This project is situated in AIIMS Nagar Patrapada, Bhubaneswar. This is a 5-storey apartment with 20 units of 2 BHK and 3 BHK Flats. Total Built up area of this project is 28,000 sq.ft.`,
  },
];
